"""Fitcast에서 사용하는 프롬프트 템플릿 모음.

프롬프트 수정은 이 파일에서만 진행합니다.
"""

from langchain_core.prompts import ChatPromptTemplate


# =========================================================
# 코디 세트 추천 프롬프트
# =========================================================

OUTFIT_PROMPT = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "너는 날씨와 개인 취향을 함께 고려하는 "
            "퍼스널 스타일리스트 'Fitcast'야.\n"
            "\n"
            "규칙:\n"
            "1. 날씨의 기온, 체감온도, 강수, 바람, 자외선을 "
            "최우선으로 고려한다.\n"
            "2. 선호 스타일의 분위기를 유지하되, 날씨에 따라 "
            "소재, 기장, 두께, 레이어드 수를 조절한다.\n"
            "3. TPO와 드레스코드에 어긋나는 아이템은 추천하지 않는다.\n"
            "4. search_keyword는 쇼핑 검색에 바로 사용할 수 있는 "
            "짧은 2~3단어 한국어로 작성한다.\n"
            "5. search_keyword에 브랜드명은 넣지 않는다.\n"
            "6. 특정 브랜드명, 상품명, 가격, 재고는 지어내지 않는다.\n"
            "7. 모든 문장은 친근한 한국어 존댓말로 작성한다.\n"
            "8. 체형 정보가 있으면 체형을 자연스럽게 보완하는 "
            "핏과 기장을 선택한다.\n"
            "9. 체형을 고려한 이유를 각 주요 아이템 설명에 "
            "한 번씩 포함한다.\n"
            "10. shape는 아래 목록에서 해당 부위의 코드만 사용한다.\n"
            "11. color_hex는 추천 색상과 가까운 실제 HEX 값으로 작성한다.\n"
            "\n"
            "## shape 코드 가이드\n"
            "{shape_guide}",
        ),
        (
            "human",
            "## 날씨\n"
            "{weather}\n\n"
            "## 기온 구간 가이드\n"
            "{temp_guide}\n\n"
            "## 스타일 가이드\n"
            "{style_context}\n\n"
            "## 사용자 정보\n"
            "- 선호 스타일: {styles}\n"
            "- TPO: {tpo}\n"
            "- 성별 핏: {gender}\n"
            "- 체형·외모: {profile}\n"
            "- 추가 요청: {note}\n\n"
            "위 조건에 맞는 코디 한 세트를 추천해 주세요.\n"
            "상의, 하의, 아우터, 신발, 가방 또는 액세서리 중 "
            "날씨와 TPO에 필요한 아이템만 포함해 주세요."
        ),
    ]
)


# =========================================================
# 챗봇 에이전트 시스템 프롬프트
# =========================================================

AGENT_SYSTEM_PROMPT = (
    "너는 날씨 기반 옷차림 상담 챗봇 'Fitcast'야. "
    "오늘 날짜는 {today}.\n"
    "\n"
    "행동 규칙:\n"
    "1. 옷차림이나 여행지 복장 질문에는 추측하지 말고 "
    "먼저 get_weather를 호출한다.\n"
    "2. 도시를 모르면 사용자에게 지역을 물어본다.\n"
    "3. '이번 주말', '내일' 같은 상대 날짜 표현은 "
    "오늘 날짜를 기준으로 YYYY-MM-DD 형식으로 해석한다.\n"
    "4. 특정 스타일이나 TPO가 언급되면 "
    "search_style_guide로 내부 가이드를 확인한다.\n"
    "5. 아이템을 추천할 때는 build_shop_links로 검색 링크를 "
    "만들어 해당 아이템 옆에 붙인다.\n"
    "6. 특정 브랜드를 물으면 브랜드의 일반적인 이미지와 "
    "스타일 수준에서만 답한다.\n"
    "7. 확인되지 않은 상품명, 가격, 할인율, 재고는 지어내지 않는다.\n"
    "8. 브랜드 검색 링크는 '브랜드명 + 아이템명' 조합으로 만든다.\n"
    "9. 사용자가 실제 상품, 브랜드, 가격을 요청하면 "
    "search_products를 호출한다.\n"
    "10. search_products 결과에 존재하는 브랜드, 상품명, 가격, "
    "링크만 보여준다.\n"
    "11. 검색 결과에 없는 상품은 추천 목록에 추가하지 않는다.\n"
    "12. 패션이나 날씨와 무관한 요청은 정중히 거절한다.\n"
    "13. 답변은 친근한 한국어 존댓말과 간결한 마크다운으로 작성한다."
)


# =========================================================
# 기본 가상 피팅 모델 생성 프롬프트
# =========================================================

# 일러스트가 아닌 실사 룩북 사진이 나오도록 매체(사진)를 최우선으로 명시
AVATAR_PROMPT = (
    "Generate a photorealistic full-body fashion lookbook PHOTOGRAPH of a "
    "real Korean model for a fashion styling service named Fitcast.\n"
    "\n"
    "User profile:\n"
    "{profile}\n"
    "\n"
    "MEDIUM (HIGHEST PRIORITY):\n"
    "- This must look like an actual photograph captured with a professional "
    "full-frame DSLR camera in a fashion e-commerce studio.\n"
    "- The result must be indistinguishable from a real online shopping mall "
    "lookbook photo of a real human being.\n"
    "- Absolutely NOT an illustration, drawing, anime, manga, webtoon, "
    "cartoon, painting, sketch, 3D render, CGI, doll, mannequin, "
    "game character, avatar or any stylized artwork.\n"
    "- No flat shading, no outlines, no line art, no cel shading, "
    "no simplified or enlarged cartoon eyes, no painterly brush strokes.\n"
    "- Render true photographic skin with visible pores, fine texture, "
    "subtle blush and natural tone variation.\n"
    "\n"
    "Face and hair:\n"
    "- Reflect the requested face impression and hairstyle from the profile.\n"
    "- Use realistic adult facial proportions of an actual Korean fashion "
    "model, with natural-sized eyes, nose and lips.\n"
    "- Use a calm neutral facial expression with a soft closed mouth.\n"
    "- Keep both eyes clearly visible unless the requested hairstyle "
    "naturally covers a small portion of the face.\n"
    "- Render individual real hair strands, natural shine, flyaways and "
    "natural hair volume.\n"
    "\n"
    "Body and pose:\n"
    "- Reflect the requested body shape, height and weight naturally with "
    "real human anatomy.\n"
    "- Full-body portrait from the top of the hair to the bottom of the shoes.\n"
    "- Stand straight and face directly toward the camera.\n"
    "- Keep the shoulders and hips nearly symmetrical.\n"
    "- Place both feet close together and pointing forward.\n"
    "- Keep both arms naturally lowered beside the body.\n"
    "- Keep both hands and all fingers visible and anatomically correct.\n"
    "- Use a neutral virtual fitting pose without walking or fashion poses.\n"
    "\n"
    "Base clothing:\n"
    "- Dress the model in a fitted light-gray sleeveless top and simple "
    "straight black leggings.\n"
    "- Show real fabric texture such as cotton weave and knit ribbing.\n"
    "- Use plain neutral clothing without patterns, logos, text, accessories "
    "or oversized silhouettes.\n"
    "- The base clothing must make later garment replacement easy.\n"
    "\n"
    "Camera and lighting:\n"
    "- Shot on a full-frame DSLR with an 85mm lens at f/8, eye-level camera, "
    "sharp focus from head to toe.\n"
    "- Soft and even front-facing softbox studio lighting with gentle "
    "natural skin highlights.\n"
    "- Real photographic depth, natural contact shadows and fabric folds.\n"
    "\n"
    "Composition:\n"
    "- Use a tall vertical composition similar to a 9:16 fashion catalogue image.\n"
    "- Center the model exactly in the canvas.\n"
    "- Leave a consistent margin above the hair and below the shoes.\n"
    "- Do not crop the hair, elbows, hands, legs or shoes.\n"
    "- Use a clean seamless warm-white studio background.\n"
    "- Add only a very soft natural grounding shadow below the feet.\n"
    "\n"
    "Quality:\n"
    "- Ultra-detailed, high-resolution, 8K fashion catalogue photograph.\n"
    "- Clear facial features and highly detailed clothing boundaries.\n"
    "- No text, logo, watermark, frame, collage or additional person."
)


# =========================================================
# AI 가상 피팅 이미지 편집 프롬프트
# =========================================================

# 편집 후에도 그림체로 바뀌지 않도록 사진 리얼리즘 유지 규칙 추가
TRYON_PROMPT = (
    "This is a high-fidelity photorealistic virtual try-on image editing task.\n"
    "\n"
    "INPUT IMAGE ORDER:\n"
    "- Image 1 is the canonical full-body Fitcast model photograph.\n"
    "- Images 2 and later are product reference images of clothing, shoes, "
    "bags or accessories.\n"
    "\n"
    "PRODUCTS TO APPLY:\n"
    "{items}\n"
    "\n"
    "USER PROFILE:\n"
    "{profile}\n"
    "\n"
    "PRIMARY TASK:\n"
    "Dress the person in Image 1 in exactly the listed products, using the "
    "product reference images as the visual source of truth.\n"
    "\n"
    "MEDIUM LOCK (HIGHEST PRIORITY):\n"
    "- The output must remain a real photograph, exactly as photorealistic "
    "as Image 1.\n"
    "- Never convert the image into an illustration, anime, cartoon, "
    "painting, 3D render, doll or stylized avatar.\n"
    "- Preserve photographic skin texture, real hair strands and real "
    "fabric texture throughout the image.\n"
    "\n"
    "MODEL IDENTITY LOCK:\n"
    "- Keep the model from Image 1 as the same person.\n"
    "- Preserve the face, facial proportions, expression, eye shape, nose, "
    "lips, skin tone and makeup.\n"
    "- Preserve the exact hairstyle, hair length, hair color, hair volume "
    "and hairline.\n"
    "- Preserve the exact body shape, height, shoulder width, waist, hips, "
    "arms and leg proportions.\n"
    "- Preserve the pose, hand position, foot position and camera angle.\n"
    "- Do not make the model slimmer, heavier, taller, shorter, younger or older.\n"
    "\n"
    "OUTFIT REPLACEMENT RULES:\n"
    "- Replace existing clothing in the same body area before applying the "
    "new product.\n"
    "- Do not layer a new top over an old top unless layering is explicitly "
    "included in the product list.\n"
    "- Do not keep old trousers, skirts, shoes, bags or accessories when a "
    "replacement product is provided.\n"
    "- Do not add unrequested fashion items.\n"
    "- Do not change the model's body to fit the clothes; fit the clothes "
    "naturally to the existing body.\n"
    "- Respect realistic garment construction, gravity, overlap and layering.\n"
    "\n"
    "PRODUCT FIDELITY:\n"
    "- Reproduce each product's exact category, color, pattern, material, "
    "silhouette, length, neckline, sleeve shape, closure, seams and details.\n"
    "- Preserve visible texture such as denim twill, knit loops, ribbing, "
    "leather grain, suede nap, cotton weave, wool fibers and satin sheen.\n"
    "- Preserve the product's intended fit, including cropped, fitted, "
    "oversized, straight, wide-leg or flared shapes.\n"
    "- Show realistic wrinkles, folds, tension and contact shadows where "
    "the garment touches the body.\n"
    "- Do not invent, alter or hallucinate logos, labels, text, prints, "
    "buttons, pockets or decorations.\n"
    "- If a logo or text is unclear in the reference, omit it rather than "
    "inventing it.\n"
    "\n"
    "TARGET VISUAL STYLE:\n"
    "- Produce a polished photorealistic Korean fashion lookbook photograph.\n"
    "- Clothing must look genuinely worn by the model, not pasted on, "
    "floating or composited incorrectly.\n"
    "- Prioritize realistic fabric texture, garment structure and natural "
    "photographic lighting on every material.\n"
    "- Keep the final image clean, modern and suitable for a fashion service UI.\n"
    "\n"
    "POSE AND FRAMING LOCK:\n"
    "- Keep exactly the same canvas size and aspect ratio as Image 1.\n"
    "- Keep the model centered in the same position.\n"
    "- Keep the same front-facing neutral fitting pose.\n"
    "- Keep the same scale and margins around the model.\n"
    "- The entire body from the top of the hair to the bottom of the shoes "
    "must remain visible.\n"
    "- Do not crop the head, hair, hands, elbows, legs, bag or shoes.\n"
    "- Keep both feet visible and close together.\n"
    "- Keep both hands anatomically correct and clearly separated from clothing.\n"
    "\n"
    "BACKGROUND AND LIGHTING:\n"
    "- Preserve the clean seamless warm-white studio background from Image 1.\n"
    "- Preserve the same soft, even studio lighting.\n"
    "- Keep only a subtle natural grounding shadow beneath the feet.\n"
    "- Do not add rooms, streets, furniture, scenery, text, borders or graphics.\n"
    "\n"
    "QUALITY CONTROL:\n"
    "- No extra fingers, missing fingers, duplicated limbs or distorted joints.\n"
    "- No merged hands, broken garment edges or shoes fused with trousers.\n"
    "- No body reshaping, face replacement or hairstyle replacement.\n"
    "- No transparent clothing unless the real product is visibly transparent.\n"
    "- No text, captions, price tags, watermarks, collages or before-and-after layout.\n"
    "- Return one finished full-body photorealistic try-on image only."
)


# =========================================================
# 업로드된 패션 사진 분석 프롬프트
# =========================================================

VISION_INSTRUCTION = (
    "이 사진 속 의류와 패션 아이템을 분석해 주세요.\n"
    "\n"
    "분석 규칙:\n"
    "1. 사진에서 실제로 확인되는 아이템만 분석한다.\n"
    "2. 각 아이템의 카테고리, 색상, 소재, 핏, 기장, 패턴과 "
    "주요 디테일을 설명한다.\n"
    "3. 브랜드는 로고, 라벨, 모노그램, 시그니처 디테일처럼 "
    "눈에 보이는 근거가 있을 때만 추정한다.\n"
    "4. 브랜드를 확인할 근거가 없으면 brand_guess는 null로 작성한다.\n"
    "5. 브랜드를 확인할 근거가 없으면 "
    "brand_confidence는 '알 수 없음'으로 작성한다.\n"
    "6. search_keyword는 비슷한 상품을 찾을 수 있는 "
    "2~4단어 한국어 검색어로 작성한다.\n"
    "7. search_keyword에 근거 없는 브랜드명은 포함하지 않는다.\n"
    "8. matching_tips에는 해당 옷과 잘 어울리는 다른 아이템과 "
    "간단한 코디 방법을 제안한다.\n"
    "9. 사진 속 인물의 신원, 인종, 나이, 매력도 등은 추정하거나 "
    "언급하지 않는다.\n"
    "10. 확실하지 않은 소재나 디테일은 단정하지 않고 "
    "'추정'이라고 표시한다."
)